---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.10.4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      # Needed for integration tests only
      - recipe[chef-solo-search]
      # Recipe under test
      - recipe[base_role::default]
    attributes:
      set_fqdn: base.vagrantup.com
      tz: Europe/Rome
